consumer:
    key: Hk2n2K8Iv2W1jEMnMNRxhfzBk8MFV32FjW0hWFT2kG5sAMES3v
    secret: jMqyIQo67F4sro1zAmvVpDFdZbwcv4CjcNdPtl6PD0jGeOxn57
oauth:
    token: jMqyIQo67F4sro1zAmvVpDFdZbwcv4CjcNdPtl6PD0jGeOxn57
    secret: FeJCOWEtbvp8yIaW5kUInq2F5wuEGrOLGns6nyjrWBHaegn5xv

blogname: masonsleeping
